version: '3.4'

services:
  qcprofstatfirebase:
    image: qcprofstatfirebase
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
      GOOGLE_APPLICATION_CREDENTIALS: key.json
    ports:
      - 5000:5000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]    
    
